[package]
name = "wetgraphics"
version = "0.2.0"
authors = ["dzil123 <5725958+dzil123@users.noreply.github.com>"]
edition = "2018"

[dependencies]
winit = "0.24"
wgpu = "0.7"
wgpu-subscriber = "0.1"
imgui = "0.7"
imgui-winit-support = "0.7"
pollster = "0.2"
phf = "0.8"

[build_dependencies]
phf_codegen = "0.8"
shaderc = "0.7"
walkdir = "2.3.2"
